import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import * as fs from "fs";
import * as path from "path";

interface DatasetInfo {
  trainImagePath: string | null;
  trainAnnoPath: string | null;
  evalImagePath: string | null;
  evalAnnoPath: string | null;
  datasetDir: string | null;
  numClasses: number;
}

interface ModelInfo {
  architecture: string;
  backbone: string;
  neck: string;
  head: string;
  numClasses: number;
  depthMult: number;
  widthMult: number;
}

interface TrainingParams {
  epochs: number;
  batchSize: number;
  baseLr: number;
  momentum: number;
  weightDecay: number;
  scheduler: string;
  warmupEpochs: number;
  workerNum: number;
  imageWidth: number;
  imageHeight: number;
  useGpu: boolean;
  gpuIds: string;
  useAmp: boolean;
  useVdl: boolean;
  snapshotEpoch: number;
  saveDir: string;
}

// Generate PaddleDetection YAML config
function generatePaddleDetectionYaml(
  dataset: DatasetInfo,
  model: ModelInfo,
  params: TrainingParams,
  configName: string
): string {
  const numClasses = dataset.numClasses || model.numClasses || 1;
  
  const yaml = `# ${configName}
# Generated by Auto Training Platform

architecture: ${model.architecture}
pretrain_weights: null

${model.architecture}:
  backbone: ${model.backbone}
  neck: ${model.neck}
  head: ${model.head}
  
${model.backbone}:
  depth_mult: ${model.depthMult}
  width_mult: ${model.widthMult}

${model.neck}:
  depth_mult: ${model.depthMult}
  width_mult: ${model.widthMult}

${model.head}:
  num_classes: ${numClasses}

# Dataset configuration
TrainDataset:
  !COCODataSet
    image_dir: ${dataset.trainImagePath || 'train'}
    anno_path: ${dataset.trainAnnoPath || 'annotations/instances_train.json'}
    dataset_dir: ${dataset.datasetDir || 'dataset/coco'}
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: ${dataset.evalImagePath || 'val'}
    anno_path: ${dataset.evalAnnoPath || 'annotations/instances_val.json'}
    dataset_dir: ${dataset.datasetDir || 'dataset/coco'}

TestDataset:
  !ImageFolder
    anno_path: ${dataset.evalAnnoPath || 'annotations/instances_val.json'}
    dataset_dir: ${dataset.datasetDir || 'dataset/coco'}

# Training configuration
epoch: ${params.epochs}

LearningRate:
  base_lr: ${params.baseLr}
  schedulers:
  - !${params.scheduler}
    max_epochs: ${params.epochs}
    warmup_epochs: ${params.warmupEpochs}

OptimizerBuilder:
  clip_grad_by_norm: 35
  optimizer:
    momentum: ${params.momentum}
    type: Momentum
  regularizer:
    factor: ${params.weightDecay}
    type: L2

# Reader configuration
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 2}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - CollateBatch: {}
  batch_size: ${params.batchSize}
  shuffle: true
  collate_batch: true
  worker_num: ${params.workerNum}
  use_shared_memory: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [${params.imageHeight}, ${params.imageWidth}], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - CollateBatch: {}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
  worker_num: ${params.workerNum}
  use_shared_memory: true

TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [${params.imageHeight}, ${params.imageWidth}], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - CollateBatch: {}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
  worker_num: ${params.workerNum}
  use_shared_memory: true

# Runtime configuration
use_gpu: ${params.useGpu}
use_amp: ${params.useAmp}
use_vdl: ${params.useVdl}
log_iter: 20
save_dir: ${params.saveDir || 'output'}
snapshot_epoch: ${params.snapshotEpoch}
`;
  return yaml;
}

// Generate PaddleClas YAML config
function generatePaddleClasYaml(
  dataset: DatasetInfo,
  model: ModelInfo,
  params: TrainingParams,
  configName: string
): string {
  const numClasses = dataset.numClasses || model.numClasses || 1;
  
  const yaml = `# ${configName}
# Generated by Auto Training Platform

# Model configuration
Arch:
  name: ${model.architecture}
  class_num: ${numClasses}

# Dataset configuration
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ${dataset.datasetDir || 'dataset'}/${dataset.trainImagePath || 'train'}
      cls_label_path: ${dataset.datasetDir || 'dataset'}/${dataset.trainAnnoPath || 'train_list.txt'}
      transform_ops:
        - ResizeImage:
            size: ${params.imageWidth}
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: ${params.batchSize}
      drop_last: False
      shuffle: True
    loader:
      num_workers: ${params.workerNum}
      use_shared_memory: True

  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: ${dataset.datasetDir || 'dataset'}/${dataset.evalImagePath || 'val'}
      cls_label_path: ${dataset.datasetDir || 'dataset'}/${dataset.evalAnnoPath || 'val_list.txt'}
      transform_ops:
        - ResizeImage:
            resize_short: ${params.imageWidth}
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: ${params.batchSize}
      drop_last: False
      shuffle: False
    loader:
      num_workers: ${params.workerNum}
      use_shared_memory: True

# Optimizer configuration
Optimizer:
  name: Momentum
  momentum: ${params.momentum}
  lr:
    name: ${params.scheduler}
    learning_rate: ${params.baseLr}
    warmup_epoch: ${params.warmupEpochs}
  regularizer:
    name: L2
    coeff: ${params.weightDecay}

# Training configuration
Global:
  epochs: ${params.epochs}
  use_gpu: ${params.useGpu}
  use_amp: ${params.useAmp}
  use_visualdl: ${params.useVdl}
  output_dir: ${params.saveDir || 'output'}
  save_interval: ${params.snapshotEpoch}
  eval_during_train: True
  eval_interval: 1
`;
  return yaml;
}

// Generate training command
function generateTrainingCommand(
  configPath: string,
  params: TrainingParams,
  framework: string,
  pythonPath: string
): string {
  const parts: string[] = [];

  // Base command with distributed launch for multi-GPU
  if (params.useGpu && params.gpuIds.includes(',')) {
    parts.push(`${pythonPath} -m paddle.distributed.launch --gpus ${params.gpuIds}`);
  } else {
    parts.push(pythonPath);
  }

  // Train script
  parts.push('tools/train.py');

  // Config file
  parts.push(`-c ${configPath}`);

  // AMP flag
  if (params.useAmp) {
    parts.push('--amp');
  }

  // VDL flag
  if (params.useVdl) {
    parts.push('--use_vdl=true');
  }

  return parts.join(' ');
}

// POST /api/training-configs/generate-yaml
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { 
      datasetId, 
      modelId, 
      projectId,
      jobName,
      trainingParams 
    } = body;

    if (!datasetId || !modelId || !projectId) {
      return NextResponse.json(
        { error: "Dataset, model, and project ID are required" },
        { status: 400 }
      );
    }

    // Get dataset info
    const dataset = await db.dataset.findUnique({
      where: { id: datasetId },
    });

    if (!dataset) {
      return NextResponse.json(
        { error: "Dataset not found" },
        { status: 404 }
      );
    }

    // Get model info
    const model = await db.model.findUnique({
      where: { id: modelId },
    });

    if (!model) {
      return NextResponse.json(
        { error: "Model not found" },
        { status: 404 }
      );
    }

    // Get project info for framework
    const project = await db.project.findUnique({
      where: { id: projectId },
    });

    if (!project) {
      return NextResponse.json(
        { error: "Project not found" },
        { status: 404 }
      );
    }

    // Get system config for paths
    const systemConfig = await db.systemConfig.findFirst();
    const framework = project.framework || "PaddleDetection";
    const workDir = framework === "PaddleClas" 
      ? systemConfig?.paddleClasPath 
      : systemConfig?.paddleDetectionPath;

    if (!workDir) {
      return NextResponse.json(
        { error: `Please configure ${framework} path in Settings` },
        { status: 400 }
      );
    }

    const params: TrainingParams = {
      epochs: trainingParams.epochs || 100,
      batchSize: trainingParams.batchSize || 8,
      baseLr: trainingParams.baseLr || 0.001,
      momentum: trainingParams.momentum || 0.9,
      weightDecay: trainingParams.weightDecay || 0.0005,
      scheduler: trainingParams.scheduler || "CosineDecay",
      warmupEpochs: trainingParams.warmupEpochs || 5,
      workerNum: trainingParams.workerNum || 4,
      imageWidth: trainingParams.imageWidth || 640,
      imageHeight: trainingParams.imageHeight || 640,
      useGpu: trainingParams.useGpu ?? true,
      gpuIds: trainingParams.gpuIds || "0",
      useAmp: trainingParams.useAmp ?? false,
      useVdl: trainingParams.useVdl ?? true,
      snapshotEpoch: trainingParams.snapshotEpoch || 1,
      saveDir: trainingParams.saveDir || `output/${jobName}`,
    };

    const datasetInfo: DatasetInfo = {
      trainImagePath: dataset.trainImagePath,
      trainAnnoPath: dataset.trainAnnoPath,
      evalImagePath: dataset.evalImagePath,
      evalAnnoPath: dataset.evalAnnoPath,
      datasetDir: dataset.datasetDir,
      numClasses: dataset.numClasses,
    };

    const modelInfo: ModelInfo = {
      architecture: model.architecture,
      backbone: model.backbone,
      neck: model.neck,
      head: model.head,
      numClasses: model.numClasses,
      depthMult: model.depthMult,
      widthMult: model.widthMult,
    };

    // Generate YAML content
    const configName = jobName || `config_${Date.now()}`;
    const yamlContent = framework === "PaddleClas"
      ? generatePaddleClasYaml(datasetInfo, modelInfo, params, configName)
      : generatePaddleDetectionYaml(datasetInfo, modelInfo, params, configName);

    // Normalize path for Windows
    const normalizedWorkDir = path.normalize(workDir);
    
    // Check if work directory exists
    if (!fs.existsSync(normalizedWorkDir)) {
      return NextResponse.json(
        { error: `Working directory does not exist: ${normalizedWorkDir}` },
        { status: 400 }
      );
    }

    // Create configs directory if not exists (recursive for Windows)
    const configsDir = path.join(normalizedWorkDir, "configs", "generated");
    try {
      if (!fs.existsSync(configsDir)) {
        fs.mkdirSync(configsDir, { recursive: true });
      }
    } catch (mkdirError) {
      return NextResponse.json(
        { error: `Failed to create directory: ${configsDir}`, message: mkdirError instanceof Error ? mkdirError.message : "Unknown error" },
        { status: 500 }
      );
    }

    // Save YAML file
    const yamlFileName = `${configName.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_.-]/g, '').toLowerCase()}.yml`;
    const yamlFilePath = path.join(configsDir, yamlFileName);
    
    try {
      fs.writeFileSync(yamlFilePath, yamlContent, "utf-8");
    } catch (writeError) {
      return NextResponse.json(
        { error: `Failed to write YAML file: ${yamlFilePath}`, message: writeError instanceof Error ? writeError.message : "Unknown error" },
        { status: 500 }
      );
    }

    // Generate training command
    const relativeConfigPath = `configs/generated/${yamlFileName}`;
    const pythonPath = systemConfig?.pythonPath || "python";
    const command = generateTrainingCommand(relativeConfigPath, params, framework, pythonPath);

    return NextResponse.json({
      success: true,
      data: {
        yamlFilePath: yamlFilePath,
        relativeConfigPath: relativeConfigPath,
        yamlContent: yamlContent,
        command: command,
        workDir: normalizedWorkDir,
      },
    });
  } catch (error) {
    console.error("Error generating YAML config:", error);
    return NextResponse.json(
      { error: "Failed to generate YAML config", message: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    );
  }
}
